/**
 * Cookie Compliance Report — Email Template
 *
 * Professional enterprise HTML email. Clean, minimal layout.
 * No marketing content or decorative gradients.
 */

export interface CookieReportEmailTemplateData {
  recipientEmail: string;
  websiteUrl: string;
}

/**
 * Builds the HTML body for the Cookie Compliance Report email.
 */
export function buildCookieReportEmailHtml(data: CookieReportEmailTemplateData): string {
  const year = new Date().getFullYear();

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Cookie Compliance Report – ${data.websiteUrl}</title>
</head>
<body style="margin:0;padding:0;background:#F8FAFC;font-family:'Segoe UI',Helvetica,Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#F8FAFC;padding:40px 0;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#FFFFFF;border:1px solid #E2E8F0;border-radius:8px;overflow:hidden;">

          <!-- Header -->
          <tr>
            <td style="background:#0F172A;padding:28px 36px;">
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td>
                    <p style="margin:0;font-size:11px;font-weight:600;color:#94A3B8;text-transform:uppercase;letter-spacing:0.12em;">Lexify AI</p>
                    <h1 style="margin:8px 0 0;font-size:20px;font-weight:700;color:#FFFFFF;letter-spacing:-0.01em;">Cookie Compliance Report</h1>
                    <p style="margin:6px 0 0;font-size:13px;color:#94A3B8;">${data.websiteUrl}</p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding:36px;">

              <p style="margin:0 0 20px;font-size:14px;color:#374151;line-height:1.7;">Hello,</p>

              <p style="margin:0 0 20px;font-size:14px;color:#374151;line-height:1.7;">
                Please find attached the <strong style="color:#0F172A;">Cookie Compliance Assessment Report</strong>
                generated by Lexify AI for <strong style="color:#0F172A;">${data.websiteUrl}</strong>.
              </p>

              <!-- Report contents list -->
              <table width="100%" cellpadding="0" cellspacing="0" style="background:#F8FAFC;border:1px solid #E2E8F0;border-radius:6px;margin:0 0 24px;">
                <tr>
                  <td style="padding:20px 24px;">
                    <p style="margin:0 0 12px;font-size:11px;font-weight:700;color:#64748B;text-transform:uppercase;letter-spacing:0.1em;">The attached report contains:</p>
                    <table cellpadding="0" cellspacing="0">
                      <tr>
                        <td style="padding:4px 0;vertical-align:top;">
                          <span style="color:#4F46E5;font-size:15px;line-height:1;margin-right:10px;">•</span>
                        </td>
                        <td style="padding:4px 0;">
                          <span style="font-size:13px;color:#374151;">Cookie inventory</span>
                        </td>
                      </tr>
                      <tr>
                        <td style="padding:4px 0;vertical-align:top;">
                          <span style="color:#4F46E5;font-size:15px;line-height:1;margin-right:10px;">•</span>
                        </td>
                        <td style="padding:4px 0;">
                          <span style="font-size:13px;color:#374151;">Compliance observations</span>
                        </td>
                      </tr>
                      <tr>
                        <td style="padding:4px 0;vertical-align:top;">
                          <span style="color:#4F46E5;font-size:15px;line-height:1;margin-right:10px;">•</span>
                        </td>
                        <td style="padding:4px 0;">
                          <span style="font-size:13px;color:#374151;">Risk summary</span>
                        </td>
                      </tr>
                      <tr>
                        <td style="padding:4px 0;vertical-align:top;">
                          <span style="color:#4F46E5;font-size:15px;line-height:1;margin-right:10px;">•</span>
                        </td>
                        <td style="padding:4px 0;">
                          <span style="font-size:13px;color:#374151;">Compliance recommendations</span>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>

              <p style="margin:0 0 8px;font-size:14px;color:#374151;line-height:1.7;">Regards,</p>
              <p style="margin:0;font-size:14px;font-weight:600;color:#0F172A;">Lexify AI</p>

            </td>
          </tr>

          <!-- Divider -->
          <tr>
            <td style="padding:0 36px;">
              <div style="height:1px;background:#F1F5F9;"></div>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:20px 36px;">
              <p style="margin:0;font-size:11px;color:#94A3B8;line-height:1.6;">
                This report was generated automatically by Lexify AI.
                It is intended solely for the addressee. If you received this message in error, please disregard it.
              </p>
              <p style="margin:8px 0 0;font-size:11px;color:#CBD5E1;">&copy; ${year} Lexify AI. All rights reserved.</p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

/**
 * Plain-text fallback for the Cookie Compliance Report email.
 */
export function buildCookieReportEmailText(data: CookieReportEmailTemplateData): string {
  return `Hello,

Please find attached the Cookie Compliance Assessment Report generated by Lexify AI for ${data.websiteUrl}.

The attached report contains:
• Cookie inventory
• Compliance observations
• Risk summary
• Compliance recommendations

Regards,
Lexify AI`;
}
