import type { DraftingSkillConfig } from "../../skill-contract.js";

export const saasSkillConfig: DraftingSkillConfig = {
  skillId: "document-types/saas",
  axis: "documentType",
  label: "SaaS Subscription Agreement",
  version: "1.2.0",
  appliesToDocTypes: ["saas"],
  requiredFacts: [
    {
      id: "servicesDescription",
      priority: "critical",
      blocking: true,
      question: "What is the name and description of the SaaS application / service?",
      reasonRequired: "SaaS agreement must clearly state the subscription service and software being accessed.",
      placeholder: "e.g. Cloud CRM platform and associated API hosting services",
      aliases: ["serviceDescription", "saasService", "applicationName"],
    },
    {
      id: "subscriptionTerm",
      priority: "critical",
      blocking: true,
      question: "What is the initial subscription term (e.g. 1 year, 12 months, auto-renewing)?",
      reasonRequired: "Subscription term dictates payment schedules and renewal windows.",
      options: ["1 year", "2 years", "3 years", "Monthly auto-renew", "Other (specify)"],
      placeholder: "e.g. 1 year",
      aliases: ["initialTerm", "termLength"],
    },
    {
      id: "feesPayment",
      priority: "critical",
      blocking: true,
      question: "What are the subscription fees and payment terms (e.g. annual in advance, Net 30 days)?",
      reasonRequired: "Fee structure defines invoicing frequency, payment windows, and late interest.",
      placeholder: "e.g. $10,000 billed annually in advance, Net 30 days",
      aliases: ["fees", "paymentTerms"],
    },
    {
      id: "uptimeCommitment",
      priority: "critical",
      blocking: true,
      question: "What is the target monthly uptime percentage (e.g. 99.9%, 99.95%)?",
      reasonRequired: "SaaS agreements require an explicit service availability target and SLA credit formula.",
      options: ["99.5%", "99.9%", "99.95%", "99.99%"],
      placeholder: "e.g. 99.9%",
      aliases: ["uptimeTarget", "availabilityTarget"],
    },
    {
      id: "dataProtectionLaw",
      priority: "critical",
      blocking: true,
      question: "Which data protection regime applies to customer personal data (e.g. UK GDPR, EU GDPR, DPDPA, CCPA)?",
      reasonRequired: "Personal data handling, sub-processor notification, and security measures depend on the governing privacy law.",
      options: ["UK GDPR / Data Protection Act 2018", "EU GDPR", "DPDPA (India)", "CCPA / CPRA", "Standard Commercial Privacy"],
      placeholder: "Select a data protection law",
      aliases: ["privacyRegime", "dataSecurity"],
    },
  ],
  safeDefaults: {
    uptimeCommitment: "99.9% monthly availability excluding planned maintenance",
    maintenanceNotice: "At least 3 Business Days advance notice for scheduled maintenance",
    paymentTerms: "Net 30 days from invoice date, payable in advance",
    latePaymentInterest: "4% per annum above the base rate of the central bank",
    annualPriceIncreaseCap: "Annual increase capped at percentage rise in CPI/RPI over preceding 12 months",
    liabilityCap: "1x total fees paid and payable by Customer in the 12-month period preceding the claim",
    dataExportWindowDays: "30 days post-termination for return or deletion of Customer Data",
    confidentialityTermYears: "5 years post-termination",
  },
  sectionBriefs: [
    {
      workUnitId: "sec-parties",
      title: "Parties and Recitals",
      purpose: "Identify SaaS Provider and Customer legal entities, corporate registration details, registered office addresses, and agreement effective date.",
      requiredContent: [
        "Provider full legal name, place of incorporation, company number, and registered office",
        "Customer full legal name, place of incorporation, company number, and registered office",
        "Agreement effective date",
        "Recitals stating Customer wishes to subscribe to Provider's software-as-a-service",
      ],
      requiredFacts: ["parties", "effectiveDate", "governingLaw"],
      requiredLegalElements: ["provider-customer-identification", "effective-date", "recitals"],
      prohibitedContent: ["Square-bracket placeholders", "Invented third parties"],
    },
    {
      workUnitId: "sec-definitions",
      title: "Definitions and Interpretation",
      purpose: "Define key commercial and technical expressions: Authorised Users, Business Day, Confidential Information, Customer Data, Documentation, Fees, Initial Subscription Term, Order Form, Personal Data, Renewal Period, Service, and SLA.",
      requiredContent: [
        "Definition of Authorised Users, Customer Data, Documentation, and Service",
        "Definition of Initial Subscription Term and Renewal Period",
        "Statutory data protection definitions (Controller, Processor, Personal Data under applicable law)",
        "Consistent capitalised defined terms",
      ],
      requiredLegalElements: ["core-saas-definitions", "data-protection-definitions"],
    },
    {
      workUnitId: "sec-service",
      title: "The Service and Licence Grant",
      purpose: "Grant non-exclusive, non-transferable, non-sublicensable licence for internal business purposes, state 24/7 availability commitments, planned maintenance notice, and feature update policies.",
      requiredContent: [
        "Non-exclusive, non-transferable licence to permit Authorised Users to access Service and Documentation",
        "Scope limited to Customer's internal business operations and seat count in Order Form",
        "Commercially reasonable endeavours for 24/7 availability excluding planned maintenance",
        "Planned maintenance advance notice covenant (minimum 3 business days)",
        "Right to modify Service provided functionality is not materially reduced",
      ],
      requiredLegalElements: ["subscription-license-grant", "seat-limitations", "availability-commitment"],
    },
    {
      workUnitId: "sec-restrictions",
      title: "Acceptable Use and Restrictions",
      purpose: "Impose strict user covenants: no viruses/malware, no system impairment or unauthorized access, no reverse engineering or decompilation, and strict prohibition on benchmarking or building competitive products.",
      requiredContent: [
        "Prohibition on storing, distributing, or transmitting viruses, malware, or unlawful content",
        "Prohibition on damaging, overburdening, or impairing Service systems or networks",
        "Strict prohibition on copying, framing, mirroring, republishing, or creating derivative works",
        "Strict prohibition on reverse engineering, decompiling, or attempting to derive source code",
        "Prohibition on accessing Service for competitive benchmarking or building competitive products",
        "Prohibition on commercial resale, timesharing, or sublicensing",
      ],
      requiredLegalElements: ["no-reverse-engineering", "no-competitive-benchmarking", "acceptable-use"],
    },
    {
      workUnitId: "sec-sla",
      title: "Service Levels and Support",
      purpose: "Define helpdesk support channels, response times, monthly uptime calculation formula, downtime exclusions, service credit tiers, and sole and exclusive remedy provisions.",
      requiredContent: [
        "Support helpdesk channels (email, phone, ticketing portal) and target response times",
        "Uptime commitment formula: ((total minutes - downtime minutes) / total minutes) * 100",
        "Downtime carveouts (planned maintenance, customer networks/equipment, force majeure)",
        "Service credit percentage formula per 1% drop below commitment",
        "Service credits as Customer's sole and exclusive financial remedy for availability failures",
      ],
      requiredLegalElements: ["uptime-commitment-formula", "service-credits-exclusive-remedy"],
    },
    {
      workUnitId: "sec-fees",
      title: "Fees and Payment Terms",
      purpose: "Specify subscription fee schedule, advance payment terms, VAT/tax exclusion, payment window, late interest rate over bank base rate, suspension rights for non-payment, and CPI-indexed annual price adjustments.",
      requiredContent: [
        "Subscription fees payable in advance (monthly, quarterly, or annually)",
        "All fees exclusive of VAT and applicable taxes",
        "Payment window from invoice date (e.g. Net 30 days)",
        "Late interest accruing daily at statutory rate above central bank base rate",
        "Provider right to suspend Service access for delinquent payments",
        "Annual renewal price adjustment capped at CPI/RPI percentage change with advance written notice",
      ],
      requiredLegalElements: ["payment-mechanics", "late-interest-clause", "price-increase-cap"],
    },
    {
      workUnitId: "sec-data-protection",
      title: "Data Protection and Privacy",
      purpose: "Govern personal data processing under applicable privacy law (UK GDPR Art. 28 / DPDPA): documented instructions, personnel confidentiality, Article 32 TOMs, sub-processor notice/objection, audit rights, and breach notice.",
      requiredContent: [
        "Controller and Processor role allocation under applicable law",
        "Process personal data strictly on documented Customer instructions",
        "Personnel confidentiality commitments",
        "Appropriate technical and organizational security measures (Article 32 TOMs)",
        "Sub-processor engagement authorization, notification of changes, and objection rights",
        "Assistance with data subject access rights and regulatory compliance",
        "Personal data breach notification without undue delay",
        "Deletion or return of personal data upon contract completion",
      ],
      requiredLegalElements: ["article-28-mandatory-clauses", "data-breach-notification", "sub-processor-rules"],
    },
    {
      workUnitId: "sec-customer-data",
      title: "Customer Data and Security",
      purpose: "Confirm Customer sole ownership of all Customer Data, grant limited operational license to Provider solely to operate service, and establish regular backup covenants.",
      requiredContent: [
        "Customer retains 100% exclusive right, title, and interest in and to Customer Data",
        "Limited, royalty-free license to Provider solely to provide and operate the Service",
        "Technical safeguards against accidental loss, unauthorized access, or destruction",
        "Regular automated backups and data export availability upon request",
      ],
      requiredLegalElements: ["customer-data-ownership", "backup-and-security-covenants"],
    },
    {
      workUnitId: "sec-ip",
      title: "Intellectual Property Rights",
      purpose: "Confirm Provider retains all intellectual property in the Service, software, algorithms, and Documentation, with no implied transfer of rights.",
      requiredContent: [
        "Provider (and its licensors) retains all IP rights in the Service, Documentation, and software",
        "No implied IP licenses or title transfer from one party to the other",
        "Customer retains all IP rights in Customer Data",
        "Feedback license: non-exclusive license to use Customer suggestions without royalty",
      ],
      requiredLegalElements: ["provider-ip-retention", "customer-data-ip-retention"],
    },
    {
      workUnitId: "sec-confidentiality",
      title: "Confidentiality",
      purpose: "Protect confidential information disclosed during the term, establish need-to-know restrictions, permitted disclosures, and survival term.",
      requiredContent: [
        "Strict duty to maintain confidentiality and prevent unauthorized dissemination",
        "Disclosures permitted only to personnel and advisers on need-to-know basis under equivalent terms",
        "Carve-outs for public domain information and disclosures required by law with advance notice",
        "Survival of confidentiality covenants for specified multi-year period post-termination",
      ],
      requiredLegalElements: ["confidentiality-obligation", "permitted-disclosures", "survival-term"],
    },
    {
      workUnitId: "sec-warranties",
      title: "Warranties and Disclaimers",
      purpose: "Provide performance warranty that Service operates in substantial conformity with Documentation, legal authority, and non-infringement, with standard disclaimer of implied warranties.",
      requiredContent: [
        "Service provided with reasonable care and skill conforming to Documentation",
        "Right and authority to enter into agreement and grant subscription licence",
        "Warranty that Service does not infringe third-party intellectual property",
        "Customer warranting authority over Customer Data",
        "Disclaimer of implied warranties of merchantability and fitness for purpose",
      ],
      requiredLegalElements: ["performance-warranty", "non-infringement-warranty", "warranty-disclaimer"],
    },
    {
      workUnitId: "sec-liability",
      title: "Limitation of Liability",
      purpose: "Set mutual aggregate monetary liability cap (12 months fees paid), exclude indirect/consequential damages, and list non-excludable liabilities (death, fraud).",
      requiredContent: [
        "Uncapped liabilities: death or personal injury from negligence, fraud, or fraudulent misrepresentation",
        "Waiver of indirect, consequential, special, and loss of profit/goodwill/data damages",
        "Aggregate financial liability capped at total Fees paid/payable in preceding 12 months",
      ],
      requiredLegalElements: ["liability-cap", "consequential-damages-waiver", "non-excludable-liabilities"],
    },
    {
      workUnitId: "sec-indemnification",
      title: "Indemnification",
      purpose: "Provide Customer IP infringement defence indemnity by Provider, and Customer indemnity for agreement breach or Customer Data IP infringement.",
      requiredContent: [
        "Provider defense and indemnification of Customer against third-party IP infringement claims",
        "Customer defense and indemnification of Provider against Customer Data infringement claims",
        "Notice, control of defense, and settlement cooperation procedures",
      ],
      requiredLegalElements: ["provider-ip-indemnity", "customer-data-indemnity"],
    },
    {
      workUnitId: "sec-term",
      title: "Term, Termination, and Effects of Termination",
      purpose: "Define Initial Subscription Term, automatic renewal, non-renewal notice window, termination for cause (material breach cure, insolvency, non-payment), and Customer Data return/deletion on exit.",
      requiredContent: [
        "Initial Subscription Term and automatic renewal for successive periods",
        "Advance written notice required to prevent automatic renewal (e.g. 30/60 days)",
        "Termination immediately for remediable material breach not cured within specified window",
        "Termination immediately for insolvency, liquidation, or administration",
        "Customer Data return or deletion within 30 days post-termination at Customer option",
        "Accrued payment and survival provisions",
      ],
      requiredLegalElements: ["term-and-renewal", "breach-and-insolvency-termination", "data-export-on-exit"],
    },
    {
      workUnitId: "sec-force-majeure",
      title: "Force Majeure",
      purpose: "Excuse performance delays caused by events beyond reasonable control including denial-of-service attacks, internet/power failures, and natural disasters, with exit rights for extended events.",
      requiredContent: [
        "Relief for circumstances beyond reasonable control",
        "Specific inclusion of power/telecom failures, internet disruptions, and denial-of-service cyber attacks",
        "Termination right if force majeure event continues continuously beyond specified days",
      ],
      requiredLegalElements: ["force-majeure-relief", "extended-event-termination"],
    },
    {
      workUnitId: "sec-misc",
      title: "General Provisions and Governing Law",
      purpose: "Boilerplate legal terms: assignment restrictions, written variation only, non-waiver, severability, third-party rights exclusion (1999 Act), notices, and exclusive jurisdiction.",
      requiredContent: [
        "Assignment restrictions: no assignment without prior written consent (group transfers excepted)",
        "Variation only in writing signed by authorized representatives",
        "Exclusion of third-party rights under Contracts (Rights of Third Parties) Act 1999",
        "Severability: invalid terms reformed to minimum extent necessary",
        "Formal written notices mechanism (first-class post, hand delivery, email)",
        "Governing law and exclusive court jurisdiction",
      ],
      requiredLegalElements: ["governing-law", "jurisdiction", "third-party-rights-exclusion", "entire-agreement"],
    },
    // Granular aliases matching exact headings in templates
    {
      workUnitId: "sec-account-registration",
      title: "3. Account registration",
      purpose: "User account credentials security and authorized user access restrictions.",
      requiredContent: ["Credential confidentiality", "Prompt notice of unauthorized access", "Authorised Users only"],
    },
    {
      workUnitId: "sec-licence-grant",
      title: "4. Licence grant",
      purpose: "Scope of subscription licence and user seat thresholds.",
      requiredContent: ["Subscription licence grant", "Authorised User limits in Order Form", "Add-on user procedure"],
    },
    {
      workUnitId: "sec-restrictions-sec",
      title: "5. Restrictions",
      purpose: "Acceptable use covenants and negative restrictions.",
      requiredContent: ["No malware/viruses", "No reverse engineering", "No competitive benchmarking"],
    },
    {
      workUnitId: "sec-support-sec",
      title: "6. Support",
      purpose: "Technical support hours, helpdesk channels, and response SLAs.",
      requiredContent: ["Support coverage hours", "Helpdesk contact channels", "Response time SLA"],
    },
    {
      workUnitId: "sec-service-levels-sec",
      title: "7. Service levels",
      purpose: "Monthly uptime commitment, downtime definitions, and service credits.",
      requiredContent: ["Uptime commitment percentage", "Downtime exclusion categories", "Service credit calculation formula"],
    },
    {
      workUnitId: "sec-fees-sec",
      title: "8. Fees and payment",
      purpose: "Invoicing schedule, payment deadlines, interest, and price adjustment caps.",
      requiredContent: ["Payment schedule", "VAT exclusion", "Late interest terms", "Annual price increase cap"],
    },
    {
      workUnitId: "sec-data-protection-sec",
      title: "9. Data protection",
      purpose: "Data processor commitments, Article 28 terms, security measures, and breach notifications.",
      requiredContent: ["Documented instructions", "Article 32 TOMs", "Sub-processor authorization", "Data breach notification"],
    },
    {
      workUnitId: "sec-customer-data-sec",
      title: "10. Customer Data",
      purpose: "Customer data ownership and backup commitments.",
      requiredContent: ["Customer Data ownership", "Operational license grant", "Regular backup schedule"],
    },
    {
      workUnitId: "sec-intellectual-property-sec",
      title: "11. Intellectual property",
      purpose: "Retention of platform IP and customer data IP.",
      requiredContent: ["Provider platform IP ownership", "Customer Data IP ownership", "No transfer of IP"],
    },
    {
      workUnitId: "sec-limitation-of-liability-sec",
      title: "14. Limitation of liability",
      purpose: "Uncapped liabilities, indirect damages exclusion, and aggregate liability cap.",
      requiredContent: ["Uncapped items (death, fraud)", "Consequential damages waiver", "12-month aggregate fee cap"],
    },
    {
      workUnitId: "sec-indemnification-sec",
      title: "15. Indemnification",
      purpose: "Provider third-party IP defense indemnity and customer indemnity.",
      requiredContent: ["Provider IP indemnity", "Customer data indemnity"],
    },
    {
      workUnitId: "sec-term-and-termination-sec",
      title: "16. Term and termination",
      purpose: "Initial subscription term, automatic renewals, and termination triggers.",
      requiredContent: ["Initial term and renewal periods", "Non-renewal notice window", "Termination for breach/insolvency"],
    },
    {
      workUnitId: "sec-effects-of-termination-sec",
      title: "17. Effects of termination",
      purpose: "Immediate cessation of service and return/deletion of customer data.",
      requiredContent: ["Cessation of access", "Customer data return or deletion within 30 days", "Surviving clauses"],
    },
    {
      workUnitId: "sec-force-majeure-sec",
      title: "18. Force majeure",
      purpose: "Relief for events beyond control and exit rights for prolonged interruptions.",
      requiredContent: ["Force majeure definitions", "Relief from liability", "Extended event exit rights"],
    },
    {
      workUnitId: "sec-general-provisions-sec",
      title: "20. General provisions",
      purpose: "Assignment, written variation, severability, and third party rights.",
      requiredContent: ["Assignment restrictions", "Written variation only", "Contracts (Rights of Third Parties) Act 1999 exclusion"],
    },
    {
      workUnitId: "sec-law-and-jurisdiction-sec",
      title: "21. Law and jurisdiction",
      purpose: "Governing law and exclusive court jurisdiction.",
      requiredContent: ["Governing law", "Exclusive court jurisdiction"],
    },
  ],
  validationRules: [
    {
      id: "saas-parties-present",
      requirement: "Agreement must identify Provider and Customer entities.",
      severity: "critical",
      checkKind: "section_present",
    },
    {
      id: "saas-customer-data-ownership",
      requirement: "Customer must retain all right, title, and interest in Customer Data.",
      severity: "critical",
      checkKind: "section_present",
    },
    {
      id: "saas-ip-protection",
      requirement: "Provider must retain all intellectual property rights in the Service and software.",
      severity: "critical",
      checkKind: "section_present",
    },
    {
      id: "saas-sla-present",
      requirement: "Agreement must specify service levels and uptime commitment.",
      severity: "critical",
      checkKind: "section_present",
    },
    {
      id: "saas-data-protection-present",
      requirement: "Agreement must contain data protection compliance terms.",
      severity: "critical",
      checkKind: "section_present",
    },
    {
      id: "saas-liability-cap-present",
      requirement: "Agreement must specify an aggregate limitation of liability cap.",
      severity: "critical",
      checkKind: "section_present",
    },
  ],
};
