import type { ReportingGuidancePackage } from "../types.js";

export const COMPLIANCE_REPORTING_GUIDANCE: ReportingGuidancePackage = {
  id: "reporting.compliance",
  version: "1.0.0",
  instructions: {
    outline: `Return JSON with version=1 and the supplied mode. Use only supplied outcome IDs as findingIds. Preserve every finding exactly once across overview sections (or across detail sections in narrative mode), and retain all required detail findings. You may create topical overview and detail groups when useful. Copy the default detailWords limits without increasing them.

Overview tables must include Requirement and Status plus one or more useful columns from the allowed set. Choose columns by the information the request asks the reader to compare. Contract provision keeps source wording near the finding; Assessment provides concise synthesis; Gap or qualification isolates what remains missing or uncertain; Recommended action is useful for remediation-oriented requests. Parties and roles, Transfer mechanism, Destination, Legal basis, and Timing are available only when the locked findings separately establish those subjects. Never use a mechanism reference as a destination, a governing-law jurisdiction as a transfer destination, or a notification trigger as a fulfilment period. If those concepts are not separately established, omit the specialized column. Other section kinds have no columns. Do not add a sources section because evidence is rendered with each finding. Limitations remain visible. Explain the design choice only in rationale.`,
    write: `Return an answer and exactly one prose row per supplied outcome ID, including satisfied requirements. The answer is two or three short sentences qualified to the reviewed scope, and is empty for table-only mode. Assessment is 8-30 words describing the actual contractual position or missing obligation, never a bare status or copied stock phrase. Explanation states what is established and what remains missing or unclear within the applicable detailWords budget. Integrate relevant request-specific answers when supported, but do not treat every dynamic answer as equally conclusive.

Write plain text only. Do not include Markdown, quotations, evidence markers, clause numbers, legal citations, IDs, statuses, counts, or actions; code owns and inserts them. Do not create new requirements, deadlines, severity, risks, recommendations, replacement clauses, facts, or legal conclusions. Missing incorporated material and technical verification failure are not contractual gaps. Do not imply complete coverage while checks remain outstanding.`,
    check: `Validate the draft and plan against the locked compliance artifacts. Reject altered statuses or meaning, unsupported assertions, invented requirements, deadlines, severity, destinations, parties, mechanisms, legal bases or recommendations, missing material qualifications, and confusion between a contract gap, unavailable material, and a technical failure. Confirm that timing concepts and transfer concepts remain distinct. This is presentation review, not renewed legal analysis.`,
    repair: `Return the complete repaired prose object. Do not change the plan's coverage, locked statuses, evidence relationships, source identity, or actions. Keep assessment descriptive and within 8-30 words. Use plain text only and respect section budgets and table-only answer behavior.`,
  },
};

