import type { ReportingGuidancePackage } from "../types.js";

export const COMPLIANCE_REPORTING_GUIDANCE: ReportingGuidancePackage = {
  id: "reporting.compliance",
  version: "1.1.0",
  instructions: {
    compose: `Return one JSON object with plan and draft fields. In plan, use version=2, the supplied mode, and copy the default paragraphLimit exactly. Give every section a unique report-local id S1, S2, and so on. Map request:primary in requestItemIds to the section that directly answers the request, and map every supplied non-user_request questionId to at least one relevant section. Use only supplied outcome IDs as findingIds and supplied question IDs as questionIds. Preserve every finding exactly once across overview sections (or across detail sections in narrative mode), and retain all required detail findings. You may create topical overview and detail groups when useful. Copy the default detailWords limits without increasing them.

Overview tables must include Requirement and Status plus one or more useful columns from the allowed set. Choose columns by the information the request asks the reader to compare. Contract provision keeps source wording near the finding; Assessment provides concise synthesis; Gap or qualification isolates what remains missing or uncertain. Parties and roles, Transfer mechanism, Destination, Legal basis, and Timing are available only when the locked findings separately establish those subjects. Never use a mechanism reference as a destination, a governing-law jurisdiction as a transfer destination, or a notification trigger as a fulfilment period. If those concepts are not separately established, omit the specialized column. For layered, detailed, or narrative output, include exactly one actions section containing every actionable outcome ID and do not also use a Recommended action table column; code will consolidate identical next steps. Short and table-only output omit the actions section and may use the action column. Other section kinds have no columns. Do not add a sources section because evidence is rendered with each finding. Limitations remain visible. Explain the design choice only in rationale.

In draft, return an answer and exactly one prose row per supplied outcome ID, including satisfied requirements. The answer is two or three short sentences qualified to the reviewed scope, and is empty for table-only mode. Assessment is 8-30 words describing the actual contractual position or missing obligation, never a bare status or copied stock phrase. Explanation states what is established and what remains missing or unclear within the applicable detailWords budget. Integrate relevant request-specific answers when supported, but do not treat every dynamic answer as equally conclusive.

Write plain text only. Do not include Markdown, quotations, evidence markers, clause numbers, legal citations, IDs, statuses, counts, or actions; code owns and inserts them. Do not create new requirements, deadlines, severity, risks, recommendations, replacement clauses, facts, or legal conclusions. Missing incorporated material and technical verification failure are not contractual gaps. Do not imply complete coverage while checks remain outstanding.`,
    check: `Validate the draft and plan against the locked compliance artifacts. Reject altered statuses or meaning, unsupported assertions, invented requirements, deadlines, severity, destinations, parties, mechanisms, legal bases or recommendations, missing material qualifications, and confusion between a contract gap, unavailable material, and a technical failure. Confirm that timing concepts and transfer concepts remain distinct. This is presentation review, not renewed legal analysis.`,
    repair: `Return the complete repaired prose object. Do not change the plan's coverage, locked statuses, evidence relationships, source identity, or actions. Keep assessment descriptive and within 8-30 words. Use plain text only and respect section budgets and table-only answer behavior.`,
  },
};
