import type { ReportingGuidancePackage } from "../types.js";

export const COMPLIANCE_REPORTING_GUIDANCE: ReportingGuidancePackage = {
  id: "reporting.compliance",
  version: "1.3.0",
  instructions: {
    compose: `Return one JSON object with plan and draft fields. In plan, use version=2, the supplied mode, and copy the default paragraphLimit exactly. Give every section a unique report-local id S1, S2, and so on. Map request:primary in requestItemIds to the section that directly answers the request, and map every supplied non-user_request questionId to at least one relevant section. Use only supplied outcome IDs as findingIds and supplied question IDs as questionIds. Preserve every finding exactly once across overview sections (or across detail sections in narrative mode), and retain all required detail findings. You may create topical overview and detail groups when useful. Copy the default detailWords limits without increasing them.

Treat the locked analysis as the complete factual boundary and organise it around what the reader needs to decide. Narrative mode contains prose and no overview table. Tabular modes use an overview table. Lite output is concise but must remain accurate; Deep output gives fuller assessment and supporting context without changing any status or conclusion.

Overview tables must include Requirement, Status, Assessment, Contract provision, and Recommended action; a sixth specialised column may be selected when the request and locked findings support it. Put assessment before evidence so the reader sees the meaning first. Parties and roles, Transfer mechanism, Destination, Legal basis, and Timing are available only when the locked findings separately establish those subjects. Never use a mechanism reference as a destination, a governing-law jurisdiction as a transfer destination, or a notification trigger as a fulfilment period. If those concepts are not separately established, omit the specialised column. Use one risks section for findings needing attention, keep each recommendation with its finding, and finish with one conclusion section. Do not create a standalone actions, limitations, or sources section. Qualifications and outstanding checks stay attached to the relevant assessment and conclusion. Explain the design choice only in rationale.

In draft, return an answer and exactly one prose row per supplied outcome ID, including satisfied requirements. The answer is two or three short, reader-facing sentences qualified to the reviewed scope, and is empty for table-only mode. Assessment is 8-30 words describing the actual contractual position or missing obligation, specifying key contract terms, numbers, or timeframes where available (e.g., "10 business days' notice", "30 days' notice"), never a bare status or copied stock phrase. Explanation leads with the practical assessment, then states what is established, why it matters, and what remains missing or unclear within the applicable detailWords budget. Thoroughly synthesize all verified bundle details, element shortfalls, and dynamic-question answers to provide high-value, fact-grounded analysis.

For recommendedAction, return an empty string for Present and Not applicable findings. For every other finding, write a specific 15-70 word remediation that directly cures the supplied missing or contradicted elements. Explicitly state what clause or proviso must be added, clarified, or reconciled, naming the responsible party, timeframe, or mechanism where established by the verified bundle. Synthesize the authored recommendation, requirementStandard, missing-element analysis, assessment, and relevant dynamic answers; never fall back to generic boilerplate such as "amend the provisions" or "address the shortfall."

The locked analysis is the complete factual and legal boundary. You may reason across and synthesize its fields to produce useful reader-facing analysis, but you must not rerun the compliance decision or introduce a new obligation, deadline, party, mechanism, severity, fact, or legal conclusion. Use selective Markdown bolding (**term**) for key contractual terms, numbers, notice periods, deadlines, and core legal concepts (e.g., **10 days' advance notice**, **5 business days**, **written authorization**, **Chapter III GDPR**). Do NOT bold entire sentences or leave paragraphs as unformatted plain text. Do not include quotations, evidence markers, clause numbers, legal citations, IDs, statuses, or counts; code owns their placement. Missing incorporated material and technical verification failure are not contractual gaps. Do not imply complete coverage while checks remain outstanding.`,
    check: `Validate the draft and plan against the locked compliance artifacts. Reject altered statuses or meaning, unsupported assertions, invented requirements, deadlines, severity, destinations, parties, mechanisms, legal bases, missing material qualifications, and confusion between a contract gap, unavailable material, and a technical failure. Confirm that every recommendedAction directly cures the supplied shortfall, is specific enough to implement, and adds nothing outside the locked requirement, missing elements, authored action, or verified answers. Reject generic recommendations that merely say to amend, review, clarify, or address a shortfall without saying what must change. Confirm that timing concepts and transfer concepts remain distinct. This is synthesis and presentation of verified analysis, not renewed legal analysis.`,
    repair: `Return the complete repaired prose object. Do not change the plan's coverage, locked statuses, evidence relationships, source identity, or legal conclusions. Keep assessment descriptive and within 8-30 words. Make each actionable recommendedAction specific to the verified missing or contradicted elements and leave it empty for Present and Not applicable findings. Use plain text only and respect section budgets and table-only answer behavior.`,
  },
};
