import type { DraftingSkillConfig } from "../../skill-contract.js";

export const msaSkillConfig: DraftingSkillConfig = {
  skillId: "document-types/msa",
  axis: "documentType",
  label: "Master Services Agreement",
  version: "1.1.0",
  appliesToDocTypes: ["msa"],
  requiredFacts: [
    {
      id: "servicesDescription",
      priority: "critical",
      blocking: true,
      question: "What services will be provided and what is the delivery method (e.g. software development/testing/consulting using remote systems)?",
      reasonRequired: "An MSA must define the scope of services and delivery mechanism under the agreement.",
      aliases: ["msaServices", "scopeOfServices", "serviceScope"],
    },
    {
      id: "paymentTerms",
      priority: "critical",
      blocking: true,
      question: "What are the remuneration and payment terms (e.g. fixed fee, monthly invoicing, Net 30 days)?",
      reasonRequired: "Invoicing procedures and remuneration terms govern services and deliverables.",
      options: ["Net 15 days", "Net 30 days", "Net 60 days"],
      aliases: ["invoicingTerms", "remunerationPrice"],
    },
    {
      id: "liabilityCap",
      priority: "critical",
      blocking: true,
      question: "What is the limitation of liability cap (e.g. 1x fees paid in preceding 12 months)?",
      reasonRequired: "Risk allocation and monetary liability caps are mandatory risk management terms.",
      aliases: ["capOnLiability"],
    },
    {
      id: "terminationNotice",
      priority: "critical",
      blocking: true,
      question: "What written notice period is required for termination (e.g. 30 days, 60 days)?",
      reasonRequired: "Termination procedures must specify the advance written notice window.",
      options: ["30 days written notice", "60 days written notice", "90 days written notice"],
      aliases: ["noticePeriod", "terminationPeriod"],
    },
  ],
  safeDefaults: {
    paymentTerms: "Net 30 days upon invoice receipt",
    liabilityCap: "1x total fees paid under the applicable SOW in the 12 months preceding the claim",
    terminationNotice: "30 days prior written notice",
    confidentialityTermYears: "3 years post-termination",
    acceptanceWindowDays: "14 calendar days from delivery",
  },
  sectionBriefs: [
    {
      workUnitId: "sec-parties",
      title: "Parties and Recitals",
      purpose: "Identify Contractor and Client entities, jurisdictions of incorporation, registered addresses, authorized representative names & job titles, and recitals.",
      requiredContent: [
        "Contractor full legal name, state of incorporation, registered address, and representative name & title",
        "Client full legal name, state of incorporation, registered address, and representative name & title",
        "Agreement effective date",
        "Recitals stating Client wishes to obtain services and Contractor wishes to provide them",
      ],
      requiredFacts: ["parties", "effectiveDate", "governingLaw"],
      requiredLegalElements: ["party-identification", "authorized-representatives", "recitals"],
      prohibitedContent: ["Invented third contracting parties", "Square-bracket placeholders"],
    },
    {
      workUnitId: "sec-definitions",
      title: "Terms and Definitions",
      purpose: "Define key terms used throughout the document including Services, Software, Deliverables, Employees, and Confidential Information.",
      requiredContent: [
        "Definition of Services specifying scope and delivery method",
        "Definition of Software and Deliverables",
        "Consistent capitalised defined terms",
      ],
      requiredLegalElements: ["services-definition", "deliverables-definition"],
    },
    {
      workUnitId: "sec-services",
      title: "Subject Matter and Rendering Services",
      purpose: "Set out Contractor's undertaking to provide services, the delivery manner, Client's remuneration duty, and the direct relationship between parties including express independent contractor status (no employment relationship).",
      requiredContent: [
        "Contractor undertaking to provide services and delivery manner",
        "Client undertaking to remunerate Contractor",
        "Rights and obligations arise directly between Contractor and Client",
        "Independent contractor relationship: no employment relationship between Client and Contractor employees",
      ],
      requiredLegalElements: ["service-undertaking", "independent-contractor-status"],
    },
    {
      workUnitId: "sec-confidentiality",
      title: "Confidentiality",
      purpose: "Protect confidential information and copyrighted materials disclosed between parties, restricting use strictly to agreement performance and prohibiting third-party disclosure without prior written consent.",
      requiredContent: [
        "Scope of confidential information and copyrighted materials",
        "Prohibition on third-party disclosure without prior written approval",
        "Standard of care (reasonable safeguards)",
        "Standard exclusions (public domain, prior knowledge, legally compelled)",
      ],
      requiredLegalElements: ["confidentiality-obligation", "third-party-disclosure-restriction"],
    },
    {
      workUnitId: "sec-ip",
      title: "Intellectual Property Rights",
      purpose: "Govern allocation of IP rights, assigning all exclusive intellectual property rights in created software, deliverables, or work product to Client.",
      requiredContent: [
        "All exclusive IP rights to all Software or deliverables created hereunder belong to Client",
        "Contractor background IP retention with perpetual license to Client",
        "Invention assignment and further assurances",
      ],
      requiredLegalElements: ["client-exclusive-ip", "work-product-assignment"],
    },
    {
      workUnitId: "sec-fees",
      title: "Remuneration and Payment Procedure",
      purpose: "Specify remuneration price structure, acceptance review of rendered services, invoicing process, payment windows, and accountability/interest for late payment.",
      requiredContent: [
        "Remuneration fee structure and pricing",
        "Acceptance testing and inspection procedure for rendered services",
        "Invoicing procedure and payment window",
        "Accountability for overdue payments and interest terms",
      ],
      requiredLegalElements: ["remuneration-terms", "acceptance-procedure", "invoicing-mechanics"],
    },
    {
      workUnitId: "sec-liability",
      title: "Limitation of Liability",
      purpose: "Cap aggregate monetary liability to agreed fees and exclude indirect, special, and consequential damages, subject to customary exceptions.",
      requiredContent: [
        "Direct damages aggregate liability cap",
        "Exclusion of indirect, special, and consequential damages",
        "Carve-outs for confidentiality breach, gross negligence, or willful misconduct",
      ],
      requiredLegalElements: ["liability-cap", "consequential-damages-waiver"],
    },
    {
      workUnitId: "sec-term",
      title: "Term and Termination",
      purpose: "Define effective date, validity term, termination by written notice with specified notice window, and immediate termination for uncured material breach.",
      requiredContent: [
        "Agreement effective date and validity term",
        "Termination by either party in written form with specified notice period",
        "Termination for material breach with cure window",
        "Accrued payment and survival obligations",
      ],
      requiredLegalElements: ["effective-date", "written-termination-notice", "cure-period"],
    },
    {
      workUnitId: "sec-force-majeure",
      title: "Force Majeure",
      purpose: "Excuse failure or delay in performance caused by circumstances beyond reasonable control of a party that could not reasonably have been foreseen or provided against.",
      requiredContent: [
        "Relief for circumstances beyond reasonable control of a party",
        "Conditions: could not reasonably have been foreseen or provided against",
        "Prompt written notice requirement",
        "Mitigation and termination if extended",
      ],
      requiredLegalElements: ["force-majeure-relief", "unforeseeability-condition"],
    },
    {
      workUnitId: "sec-misc",
      title: "Dispute Resolution, Amendments, and Governing Law",
      purpose: "Establish mandatory good-faith negotiation before formal dispute filing, governing law of the designated state/region, submission to jurisdiction / arbitration venue with specified language, and written amendment requirement.",
      requiredContent: [
        "Mandatory good-faith negotiations to settle disputes amicably",
        "Governing law of the designated state/region",
        "Submission to jurisdiction or arbitration with specified language",
        "Amendments and supplements valid only by written agreement of both parties",
        "Entire agreement and counterpart execution",
      ],
      requiredLegalElements: ["amicable-negotiation-first", "governing-law", "written-amendments-only"],
    },
    // Granular aliases for matching exact numbered headings from user templates
    {
      workUnitId: "sec-subject-matter",
      title: "Subject Matter of Agreement",
      purpose: "Specify what services will be provided, delivery manner, and remuneration undertaking.",
      requiredContent: ["Services to be provided", "Delivery manner", "Remuneration undertaking"],
    },
    {
      workUnitId: "sec-rendering-services",
      title: "Rendering Services",
      purpose: "Rights and obligations between parties, including independent contractor relationship.",
      requiredContent: ["Rights and obligations arise directly between parties", "No employment relationship with Client"],
    },
    {
      workUnitId: "sec-acceptance",
      title: "Acceptance of Rendered Services and Payment Procedure",
      purpose: "Invoicing process, acceptance verification, and payment timeline.",
      requiredContent: ["Acceptance procedure", "Invoicing process", "Late payment terms"],
    },
    {
      workUnitId: "sec-amendments",
      title: "Amendments",
      purpose: "Specify amendment procedure (written agreement only).",
      requiredContent: ["Amendments and supplements only in written agreement of both parties"],
    },
    {
      workUnitId: "sec-jurisdiction",
      title: "Jurisdiction",
      purpose: "Negotiation efforts, applicable law, and jurisdiction/arbitration.",
      requiredContent: ["Reasonable efforts to settle disputes by negotiation", "Governing law", "Jurisdiction / arbitration venue"],
    },
  ],
  validationRules: [
    {
      id: "msa-parties-present",
      requirement: "Agreement preamble must identify Contractor and Client entities with authorized representatives.",
      severity: "critical",
      checkKind: "section_present",
    },
    {
      id: "msa-confidentiality-present",
      requirement: "Agreement must include confidentiality obligations.",
      severity: "critical",
      checkKind: "section_present",
    },
    {
      id: "msa-ip-present",
      requirement: "Agreement must include intellectual property rights allocation.",
      severity: "critical",
      checkKind: "section_present",
    },
    {
      id: "msa-force-majeure-present",
      requirement: "Agreement must include a force majeure clause.",
      severity: "warning",
      checkKind: "section_present",
    },
  ],
};

