import type { AnalysisSkillConfig } from "../types.js";

export const generalReviewSkill: AnalysisSkillConfig = {
  skillId: "general-review",
  label: "General Contract Review",
  version: "1.0.0",
  appliesToDocTypes: [
    "msa",
    "nda",
    "sla",
    "service-agreement",
    "commercial-agreement",
    "unknown",
  ],
  triggerPhrases: [
    "risk audit",
    "comprehensive",
    "review agreement",
    "flag risk",
    "liability",
    "indemnity",
    "termination",
    "obligations",
    "dispute",
  ],
  promptLibraryIds: ["general-review"],
  clauseTypes: [
    "indemnity",
    "limitation_of_liability",
    "termination",
    "governing_law",
    "confidentiality",
    "payment",
    "dispute_resolution",
    "assignment",
    "force_majeure",
    "warranties",
  ],
  expectedClauses: [
    {
      clauseType: "limitation_of_liability",
      severityIfMissing: "high",
      findingCategory: "missing_limitation_of_liability",
      textSynonyms: ["limitation of liability", "liability shall not exceed", "cap on liability"],
    },
    {
      clauseType: "indemnity",
      severityIfMissing: "high",
      findingCategory: "missing_indemnity",
      textSynonyms: ["indemnif", "hold harmless"],
    },
    {
      clauseType: "termination",
      severityIfMissing: "medium",
      findingCategory: "other_known_risk",
      textSynonyms: ["terminat", "notice period"],
    },
    {
      clauseType: "governing_law",
      severityIfMissing: "medium",
      findingCategory: "other_known_risk",
      textSynonyms: ["governing law", "jurisdiction"],
    },
  ],
  riskCategories: [
    { category: "uncapped_liability", guidance: "Liability is unlimited or effectively uncapped." },
    { category: "one_sided_indemnity", guidance: "Indemnity obligations fall disproportionately on one party." },
    { category: "unilateral_termination", guidance: "Termination rights favor one party without reciprocal rights." },
    { category: "ambiguous_definition", guidance: "Defined terms or obligations are vague or unmeasurable." },
    { category: "missing_limitation_of_liability", guidance: "No limitation of liability clause identified." },
    { category: "missing_indemnity", guidance: "No indemnity clause identified where expected." },
    { category: "other_known_risk", guidance: "Other material contractual risk." },
  ],
  regimeRules: [],
  defaultOperation: "risk_flag",
};
